package com.example.photoapp;

import android.Manifest;
import android.app.Activity;
import android.app.Dialog;
import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.widget.Toolbar;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class UserFormActivity  extends BaseActivityToolbar {


    String[]  containerType = {"DC","HC","FR","OT","RF","HARDTOP","PF","OP","TK","HT","CF","GP","DV","FR(ODC)","OS","ODC","TC","HQ","GL","HQGOH","HQRF","GLGOH"};
    String[]  containerSize = {"20","40","45"};
    String[]  locations = {"Dadri","Mundra_1","Mundra_2","Kolkata","Veshvi","Mundra_Empty_Park"};
    String[]  loadedActivities;
    String[] loadedCycles;
    String[] loadedSurveyors;

    ArrayList<String>  surveyors = new ArrayList<String>();
    ArrayList <String>  activities = new ArrayList<String>();
    ArrayList <String>  cycles = new ArrayList<String>();
    String[]  containerStatus = {"Damaged","Sound"};
    String[]  shippingLine = {"7 ZONE SHIPPING LINE (I) PRIVATE LIMITED","88 CUBE LOGISTICS","A PLUS BOX LINE","AAHIL SHIPPING & LOGISTICS","ABLE SHIPPING","ACE","INDUS","ABS SHIPPING AND CONTAINER SERVICES PRIVATE LIMITED","ACCORD SHIPPING","ACE GLOBAL LINE","AEGON SHIPPING INDIA PRIVATE LIMITED","AFLOAT CONTAINER LINES INDIA PRIVATE LIMITED","AISSA MARITIME PVT LTD","AIYER SHIPPING AGENCY PRIVATE LIMITED","AKKON LINES","AL AZEEZ SHIPPING SERVICES LLC","ALBATROSS SHIPPING PVT LTD","BALAJI LINE","ALBATROSS SHIPPING PVT LTD","BALAJI LINE","ALISPED INDIA PVT LTD","ALLIANCE CONTAINER LINE LLP","ALLIANCE MARINE AGENCIES","ALLIED CONTAINER LINE","ALPHA MARINE","ALPHA OMEGA SHIPPING SERVICES PRIVATE LIMITED","ALX SHIPPING","AMA LINE","AMFICO AGENCIES PRIVATE LIMITED","ANAND SHIPPING LINES PVT LTD","ANL SINGAPORE PTE LTD","ANL INDIA","AMERICAN PRESIDENT LINE","APSL LINES PRIVATE LIMITED","AQUA CONTAINER LINE","AQUATIC FREIGHTS PRIVATE LIMITED","ARIES SHIPPING AND LOGISTICS","ARMITA INDIA SHIPPING PRIVATE LIMITED","ARVIA SHIPPING PRIVATE LIMITED","ASCO SHIPPING LINES","ASIAAN TIGER LINES INDIA PVT LTD","ASN SHIPPING","ASR INDIA PVT LTD","ASR INDIA PVT LTD","ASYAD LINE","ATL SHIPPING AND LOGISTICS","ATLANTIC CONTAINER LINE","AUSTERE SHIPPING AND LOGISTICS PVT.LTD.","AVANA LOGISTICS LIMITED","AVS AIR-SEA SERVICES PVT LTD","UNKNOWN","AYER SHIPPING AGENCY PVT LTD","BABAJI SHIVRAM CLEARING AND CARRIERS PVT LTD","UNKNOWN","INTERMARK","CHINA NAVIGATION COMPANY PTY","UNITED AFRICA FEEDER LINES","BENLINE","BHAVANI SHIPPING","BHAVANI SHIPPING","BSS","BHAVANI SHIPPING","BILANDER LOGISTICS PVT LTD","BLUE WORLD SHIPPING AGENCIES PVT LTD","BLUEMARLIN CONTAINER LINE PRIVATE LIMITED","BLUEPETER SHIPPING PRIVATE LIMITED","BOX TRADE","BOXSMART SHIPPING PRIVATE LIMITED","BRILLIANT SHIPPING SERVICES PVT . LTD","BALAJI LINE","BULKHAUL","BURAQ SHIPPING LINE LLP","CAPELINE SHIPPING INDIA PRIVATE LIMITED","CAPLINE SHIPPING","CARAVEL LOGISTICS PVT LTD","CARE CONTAINER LINES PRIVATE LIMITED","CARGO PLANE SHIPPING LINES","CARGO PLANE SHIPPING LINES","CARGOSOL LOGISTICS PVT LIMITED","CARICO SHIPPING PRIVATE LIMITED","CASTO SHIPPING LINE LLP","CCL","CEL LOGISTICS PVT.LTD.","CEYLINE SHIPPING SERVICES PVT LTD","CGL LOGISTICS PVT LTD","CHAIKAIT AGENCIES PVT LTD","CHAKIAT AGENCIES PVT LTD","CHAIKAIT AGENCIES PVT LTD","CHAKIAT AGENCIES PVT LTD","CHARTERING RORO LLP","CHINA UNITED LINES LTD.","CLEAR FREIGHT INTERNATIONAL PRIVATE LIMITED","CLIFFLINE SHIPPING INDIA PVT LTD","CMA CGM","UNKNOWN","COMBINED SHIPPING SERVICES PVT LTD","CONIFER LOGISTICS PRIVATE LIMITED","CONOCEAN12 AGENCIES INDIA PVT LTD","CORDELIA CONTAINER SHIPPING LINE PRIVATE LIMITED","CORTEN SHIPPING INDIA PVT LTD","COSCO INDIA SHIPPING PVT LTD","CREST CONTAINER LINES PVT LTD","CSAV","CSTAR LINE","CULINES","DAHNAY LOGISTICS PVT LTD","DBC SONS GUJARAT PRIVATE LIMITED","DECCAN TRANSCON LEASING PVT LTD","DECCAN TRANSCON SHIPPING LLP","DEMCO CONTAINER LINE PVT LTD","DENIZ LOGISTICS LLP","DGS LOGISTICS AND SHIPPING (INDIA) PRIVATE LIMITED","DIAMOND MARITIME AGENCY PVT.LTD.","DIAMOND MERITIME AGENCY","DOLPHIN SHIPPING LINE","DR SHIPPING","E SHIP GLOBAL LOGISTICS","E2 CONTAINER LINE","EAGLETAINER LOGISTICS PTE LTD","ECON SHIPPING LINE","ECON LINE","ECONSHIP TECH PRIVATE LIMITED","EFFICIENT MARINE SERVICES LLP","EIS EXIM INTERNATIONAL PVT LTD","ELITE OCEAN LINE PRIVATE LIMITED","EMINENCE CONTAINER LINES","AMFICO AGENCIES PRIVATE LIMITED","DOEHLE DANAUTIC","EMIRATES SHIPPING AGENCIES (INDIA) PVT LTD","UNKNOWN","EMKAY","ACE","EMU LINES PRIVATE LIMITED","ENTRUST SHIPPING SERVICES PRIVATE LIMITED","ESAEL SHIPPING AGENCIES","EVER RADIANT SHIPPING AND LOGISTICS","EVERBRIDGE LOGISTICS PVT LTD","EVERGREEN SHIPPING AGENCY (INDIA) PVT LTD","EVERSHINE CONTINER LINE PRIVATE LIMITED","SIT","EXCEL SHIPPING AGENCIES","EXCELLER SHIPPING AND LOGISTICS PVT LTD","EXPRESSWAY CARGO MOVERS PVT LTD","EXPRESSWAY SHIPPING","FAIR FREIGHT LINE PRIVATE LIMITED","FAIR FREIGHT LOGISTICS","FAREDEAL SHIPPING AGENCIES","FASTEX CONTAINER","FIRST MARITIME PVT LTD","FML CONTAINER LINES","PAT","FORBES CONTAINER LINE","FOURCEE","FREIGHT CONNECTION INDIA","J M BAXI","FREIGHT SYSTEM ( INDIA ) PRIVATE LIMITED","FULCRUM SHIPPING","G G MARINE CONTAINERS PRIVATE LIMITED","G MAC GLOBAL MARITIME AGENCY PRIVATE LIMITED","GAC SHIPPING (INDIA) PVT LTD","HOYER LINE","GALLEON WESTERN SHIPPING PRIVATE LIMITED","GHUMLI SHIPPING AGENTS PRIVATE LIMITED","GIGA SHIPPING INDIA PRIVATE LIMITED","GIL SHIPPING SERVICES PRIVATE LIMITED","GLACIER SHIPPING AND LOGISTICS LLP","GLITTER SHIPPING SERVICES","GLOBELINK WW INDIA PVT LTD","BALTIC","GAP","GMLLC","GMPL","GOODRICH","VASCO","VASCO GLOBAL MARITIME","GREENWICH MERDIAN LOGISTICS PVT LTD","GROW SHIPPING LINE","GSR SHIPPING PRIVATE LIMITED","HAMBURG SUD","HANJIN SHIPPING","HAPAG LLOYD INDIA PVT.LTD.","HARVARD GLOBAL LOGISTICS LIMITED","HAVEN ENTERPRISES","HEUNG A SHIPPING CO LTD","TS LINE","HUB & LINKS LOGISTICS (I) PVT LTD","HUB AND LINKS LOGISTICS INDIA PVT LTD","HVS SHIPPING AGENCY PVT LTD","HYUNDAI MERCHANT MARINE","IAL","IGM SHIPPING PRIVATE LIMITED","INBOX LOGISTICS SOLUTIONS PRIVATE LIMITED","INDIA SHIPPING AGENCIES","INDIAL SHIPPING PRIVATE LIMITED","UNKNOWN","INDUS","INOX SHIPPING LINE PTE LTD","INTER GLOBE MARINE","INTERASIA","INTERFLOW (TCS) LTD","INTERGULF SHIPPING LINE PRIVATE LIMITED","BAY LINES","INTERRAIL INDIA PVT LTD","IRISL INDIA PVT. LTD.","ISS SHIPPING INDIA PRIVATE LIMITED","J M BAXI","THE SHIPPING CORPORATION OF INDIA LTD","J STAR SHIPPING LLP","BULKHAUL","JAMES MACKINTOSH AND CO. PVT. LTD.","UNKNOWN","JETSHIPPING & LOGISTICS GLOBAL INDIA PVT LTD","JJ MES","JOVIAN CONTAINER LINES","JSK SHIPPING AND LOGISTICS","JUPITER CONTAINER LINES(JOVIAN LINE)","K LINE","K STAR SHIPPING LINE","KALASH GLOBAL LOGISTICS PRIVATE LIMITED","KCA LINES","KIA CONTAINER LINES PRIVATE LIMITED","KING STAR FREIGHT PVT LTD","KINSHIP SERVICES INDIA PVT LTD","KISHORCHANDRA KALYANJI AGRI LLP","KMS MARITIME INDIA PVT LTD","KN OCEANS PRIVATE LIMITED","KODI SHIPPING AGENCIES PVT LTD","UNKNOWN","UNKNOWN","KOREA MARINE TRANSPORT CO. LTD.","KUEHNE NAGAL PVT LTD","LANCER CONTAINER LINES LIMITED","LAUREL NAVIGATION LTD","LCL LOGISTIX (I) PVT LTD","LEADEDGE LOGISTICS PRIVATE LIMITED","LEL","LEGEND LOGISTICS","LEGEND SHIPPING","LEOSTAR SHIPPING LINES PRIVATE LIMITED","LESCHACO INDIA PVT LTD","LIVRO SHIPPING PRIVATE LIMITED","LOGENIX INTERNATIONAL PVT LTD","M CONTAINER LINE","MAAS CONTAINER LINE","AMFICO AGENCIES PRIVATE LIMITED","MAERSK","SAFMARINE","MAJESTIC MARITIME PRIVATE LIMITED.","MAK","MARIANA EXPRESS LINES","MARINE CONTAINER LINE","MARINE CONTAINER SERVICES","MARINE CONTAINER SERVICES","MARINETRANS INDIA LTD","RCL AGENCIES (INDIA) PVT. LTD.","MAS SHIPPING AGENCIES PVT LTD","UNKNOWN","MASTER LOGITECH PVT LTD","MAXICON CONTAINER LINE","MAXICON SHIPPING AGENCIES PVT LTD","MAXIM SHIPPING PVT LTD","MAXX SERVICES","MCT","MERCHANT LINE","CSCL","MERCHANT SHIPPING SERVICES PVT LTD","MERIDIAN LINE","LINEA MESSINA","MGL","MGR CONTAINER LINE INDIA PVT LTD.","MILAHA INTEGRATED MARITIME AND LOGISTICS W.W.L.","MISC BERHAD","MITRANS CONTAINER LINES CO LTD","MITSUI OSKLINES (INDIA) PVTLTD","MLI CONTAINER LINES","AYER SHIPPING AGENCY PVT LTD","CAPELINE SHIPPING INDIA PRIVATE LIMITED","MLI LOGISTICS INDIA PVT LTD","NERIDA SHIPPING PRIVATE LIMITED","POLARIS SHIPPING LINES LLP","SAMUDERA ALLIANCE LINE PRIVATE LIMITED","UCL SHIPPING PRIVATE LIMITED","Z LINE","MONTER SHIPPING AND LOGISTICS (INDIA) PRIVATE LIMITED","MOONSTAR LINES PVT LTD","MORE SHIPPING AND LOGISTICS","MOXIE SHIPPING & LOGISTICS","MS TANK LOGISTICS INDIA PRIVATE LIMITED","MSA GLOBAL LOGISTICS PRIVATE LIMITED","MSA LINE","MSB LINE","MSC","MUSKAN CONTAINER LINES PVT LTD","N STAR CONTAINER LINES PVT LTD","NAVIO SHIPPING PRIVATE LIMITED","NAVIS SHIPPING INDIA PRIVATE LIMITED","NECO LINE ASIA","NEPTUNE CONTAINER LINES","NERIDA SHIPPING PRIVATE LIMITED","NEW GOLDEN SEA SHIPPING PTE. LTD.","NEWPORT INDIA PRIVATE LIMITED","NH SHIPPING PRIVATE LIMITED","NLS AGENCY (INDIA) PVT.LTD.","NOBLE SHIPPING PVT. LTD.","NOMA INFRASTRUCTURE PRIVATE LIMITED","NOVEL LINE","NYK LINE (I ) LTD","OASIS SHIPPING PVT. LTD.","TS LINE","OASIS SHIPPING PVT. LTD.","OCEAN GENERATION SHIPPING PVT LTD","OCEAN NETWORK EXPRESS","OSO","OCEANAXIS CONTAINER LINES","OCEANIC STAR LINE","OCEANMASTERS MARINE SERVICES PVT LTD","OEL EXPRESS INDIA PRIVATE LIMITED","MAERSK","OM FREIGHT FORWARDERS P LTD","OMAN CONTAINER LINES","UNKNOWN","OMEGA SHIPPING AGENCIES PVT.LTD.","WAN HAI LINES LIMITED","OMTRANS LOGISTICS","OPAL ASIA","PAL","GOSS","OPD","OPUS DEI LOGISTICS INDIA PVT LIMITED","LMT","OOCL","UNKNOWN","ORIENT SHIP AGENCY PVT LTD","HYUNDAI MERCHANT MARINE","OSL","OSPREY SHIPPING PRIVATE LIMITED","PACIFIC SELATAN AGENCY SDN BHD","PAL","PAN LLOYD LINES","PAN ASIA LINE","PANGLOBE SHIPPING SERVICES PVT LTD","PARAMOUNT SEALINK PVT LTD","CEEKAY","DELMAS","PAREKH MARINE AGENCIES PVT. LTD.","UNKNOWN","PENT OCEAN CONTAINER INTERNATIONAL (PRIVATE) LIMITED","PENTAGON LINES PVT LTD","PERMA CONTAINER U.K LINE","PACIFIC INTERNATIONAL LINES","PND MARITIME PVT LTD","POLARIS SHIPPING LINES LLP","POLESTAR FREIGHT SERVICE PVT LTD","PORTTRADE SHIPPING AGENCIES PVT LTD","PTS","POSEIDON SHIPPING AGENCIES (PVT) LTD","BLUE WATER LINES","POSEIDON SHIPPING AGENCY PVT LTD","QATAR NAVIGATION","PRIME MARITIME","PRIMO SHIPPING AGENCIES PRIVATE LIMITED","PRINCIPAL CONTAINER LINE PRIVATE LIMITED","PROCOM LOGISTICS PVT LTD","PROGREDIRE SHIPPING PRIVATE LIMITED","PRO","PROGREDIRE SHIPPING PRIVATE LIMITED","HDS","PRUDENTIAL GLOBAL LOGISTICS PVT LTD","PRUDENTIAL LINE","UNKNOWN","PSN CONTAINER PVT LTD","QATAR MARITIME","RADIANT LINE","RAMA VESSEL HANDLERS PVT.LTD.","RASHI SHIPPING SERVICES PVT LTD","RAS","RATHA SHIPPING AGENCIES (INDIA) PRIVATE LIMITED","RCL AGENCIES (INDIA) PVT. LTD.","REEL SHIPPING LLC","RELIABLE SHIPPING SERVICES","RELIANCE","RHENUS LOGISTICS INDIA PRIVATE LIMITED","RISTAR LOGISTICS LLP","RR SHIPPING PVT LTD","RTW GLOBAL LOGISTICS","S M CONTAINER LINE PRIVATE LIMITED","COSCO INDIA SHIPPING PVT LTD","A OLD DO NOT USE","SAFFRON CONTAINER LINES I PVT LTD","SAG TRANSLINE","SAI SHIPPING CO PRIVATE LIMITED","SALZ LOGISTICS PRIVATE LIMITED","ETHIOPINAN SHIPPING AND LOGISTICS ENT","HOYER GLOBAL TRANSPORT B V","SAMSARA SHIPPING PVT LTD","SAMUDERA ALLIANCE LINE PRIVATE LIMITED","SAMUDERA SHIPPING LINE LTD","SANCO","SAR TRANSPORT SYSTEMS PRIVATE LIMITED","SARANG MARITIME LOGISTICS PVT LTD","SARJAK","SATKAR CONTAINER LINE PVT LTD","UNKNOWN","SEA CARE SHIPPING PVT LTD","SEA EXPRESS SHIPPING AGENCIES PRIVATE LIMITED","RAS","SEA GOLD LOGISTICS PRIVATE LIMITED","SEA HAWK LINES PVT LTD","SEAHAWK LOGISTICS PVT LTD","SEA LEAD SHIPPING","SEA LLOYD SHIPPING LINES PRIVATE LIMITED","SANCO","SEA MARINE LOGISTICS PVT LTD","SML","SEA PRIDE LINE","DAL","QNL","SEA TRADE SHIPPING INDIA PVT LTD","SEAASIA LOGISTICS INDIA PVT LTD","SEABRIDGE MARINE AGENCIES PRIVATE LIMITED","SEABRIDGE MARINE AGENCIES PRIVATE LIMITED","SEABRIDGE MARINE AGENCIES PRIVATE LIMITED","SEACARE FORWARDERS","SEAGOLD SHIPPING (INDIA) PRIVATE LIMITED","SEAHAWK LOGISTICS PVT LTD","SEAHORSE SHIP AGENCIES PVT. LTD.","SSA","SEAHORSE SHIP AGENCIES PVT. LTD.","SEAIKON SHIPPING AGENCY","SEAKING SHIPPING LLC","SEAPORT LINES (INDIA) PVT LTD","SEAPORT LINES (INDIA)PVT LTD","SEASPEED CONTAINER LINES PVT. LTD.","SEAWAY SHIPPING LINE","SEAWAYS LINER AGENCIES PVT. LTD.","SEAWORLD SHIPPPING AND LOGISTICS PRIVATE LIMITED","SEAXPERT LINES","SEEFAR SHIPPING PVT LTD","SEVEN HILLS SHIPPING PRIVATE LIMITED","SGS SHIPPING AGENCIES PVT LTD","SHAL","SHAL SEA SHIPPING LLC","UNKNOWN","SHARP LOGISTICS PRIVATE LIMITED","SHIPPING WORLD SERVICES PRIVATE LIMITED","SHREYAS RELAY SYSTEMS LTD","SHREYAS RELAY SYSTEMS LTD","SHREYAS SHIPPING AND LOGISTICS LTD","SHRI VAIBHAVI LOGISTICS","SHYAMA SHIPPING SERVICES","SILMAR SHIPPING","SIMA MARINE INDIA","AISSA MARITIME PVT LTD","SIMPLE SHIPPING SOLUTIONS PVT LTD","SINOKOR MERCHANT MARINE","SITARA SHIPPING LTD","SKY BLISS SHIPPING AGENCY PRIVATE LIMITED","SM LINE","SMART MARINE SERVICES PVT LTD","SMARTLOG","SMERA LINES","SO CONTAINER LINE PVT LTD","SPARCON LINES PRIVATE LIMITED","SPARXX MARITIME AND LOGISTICS PRIVATE LIMITED","ST JOHN FREIGHT SYSTEMS LTD","STALWART SHIPPING AND LOGISTICS","STAR LINE SHIPPING","STAR SHIPPING SERVICES","SUNDERSONS LOGISTICS PRIVATE LIMITED","MGR CONTAINER LINE INDIA PVT LTD.","SUNSTAR SHIPPING SERVICES","SUPER CONTAINER LINE","SWIFT LINE","SUPREME CONTAINER LINE","SURF WAVES SHIPPING LLP","SWEN CONTAINER LINE","NEPTUNE CONTAINER LINES","SUPER CONTAINER LINE","SWIFT LINE","SYSTEMATIC LOGISTICS (SLPL)","TAURUS LINES PRIVATE LIMITED","TG TERMINALS CFS VESHVI","THE SHIPPING CORPORATION OF INDIA LTD","TIME GLOBAL VENTURES PRIVATE LIMITED","TIMES CONTAINER LINE","TLPL INTEGRATED SHIPPING SERV P LTD","TLPL SHIPPING AND LOGISTICS PVT. LTD.","TNS LINE","UNKNOWN","TOMS SHIPPING AND LOGISTICS PVT LTD","TRANCEMARINE AND CONFREIGHT LOGISTICS PVT. LTD","TRANS ASIAN SHIPPING SERVICES PVT LTD.","UNKNOWN","UNKNOWN","TRANS ASIAN SHIPPING SERVICES PVT LTD.","TRANSAFE GLOBAL LIMITED","TRANSLINER MARINE PVT LTD","TRANSLINER MARITIME PVT LTD","TRANSMAR INTERNATIONAL SHIPPING COMPANY","TRANSMARINE CARGO SERVICES PVT LTD","TRANSNATIONAL SHIPPING INDIA PVT LTD","TRANSORIENT SHIPPING PVT LTD","TRANSVISION SHIPPING PVT LTD","TSP","TRANSWORLD","BLPL","TRANSWORLD","TRANSWORLD GLOBAL LOGISTICS AND SOLUTION PVTLTD","TRANSWORLD GLSPL","TRANSWORLD GLOBAL LOGISTICS AND SOLUTION PVTLTD","BLPL","NLS AGENCY (INDIA) PVT.LTD.","BALAJI LINE","LINEA MESSINA","TRANSWORLD SHIPPING AND LOGISTICS LTD","TRIKOM SHIPPING PVT LTD","TRISTAR LOGISTICS (INDIA) PVT LTD","TRISTAR LOGISTICS INDIA PVT LTD","TS LINE","UNITED CONTAINER LINES (INDIA) PRIVATE LIMITED","UNICON LOGISTICS INDIA PVT LTD","UNIFEEDER AGENCIES INDIA PRIVATE LIMITED","UNILLOYD LOGISTICS INDIA PVT LTD","UNITED ARAB SHIPPING CO","UNITED CONTAINER LINES (INDIA) PRIVATE LIMITED","K LINE","UNITED LINER SHIPPING SERVICES LLP","UNKNOWN","V BIRD SHIPPING AGENCIES PVT. LTD.","V CAN LOGISTICS SOLUTIONS PVT LTD","V S AND B CONTAINERS PVT LTD","VASCO","VEDANT CONTAINER LINE INDIA PVT LTD","VICTOR AND CO","VICTOR EXPRESS LINE","VIRBHADRA CONTAINER LINES","VISION CONTAINER LINE PVT LTD","VISTAR SHIPPING LLC","VOLLAN SHIPPING PVT LTD","VOLTA CONTAINER LINE PRIVATE LIMITED","VOYOX SHIPPING AND LOGISTICS PVT LTD","VUDIX SHIPPING INDIA PVT LTD","WAN HAI LINES LIMITED","WATERWINGS CONTAINER LINES PVT LTD","WHITE STAR SHIPPING PVT LTD","WILHELMSEN MARITIME SERVICES PVT LTD.","WINASIA MARITIME PVT LTD","WINOCEAN MARITIME PVT LTD","WINWIN MARITIME LIMITED","WORLDWIDE TRADING COMPANY PVT LTD","XTRANS LOGISTICS PVT LTD","XXXXXNOVEL LINES","GOSS","YANG MING LINE","YTL","NYK LINE (I ) LTD","YUSEN LOGISTICS","Z LINE","ZIM LINE","Z WORLD","ZIM WORLD FREIGHT","ZODIAC SHIPPING AGENCY (INDIA) PVT LTD","LINE","MAERSK","SAFMARINE INDIA PRIVATE LIMITED","AAHIL SHIPPING AND LOGISTICS PVT LTD","ABLE CONTAINER LINE","INDUS","SARANG MARITIME LOGISTICS PVT LTD","ACURA SHIPPING","AEGON SHIPPING INDIA PVT LTD","AFLOAT CONTAINER LINES INDIA PRIVATE LIMITED","ASM LINE","AIYER SHIPPING AGENCY PVT. LTD.","AIYER SHIPPING AGENCY PVT. LTD.","ALLIGATOR LINE","ALX","ALX","BALAJI SHIPPING","ALLIANCE CONTAINER LINE LLP.","ALX","AMERICAN PRESIDENT LINE","APS","ARMITA INDIA SHIPPING PVT LTD","ARVIA SHIPPING PRIVATE LIMITED","ASIATIC CONTAINER LINES (I) PVT LD","ASIATIC CONTAINER LINES (I) PVT LD","ASN SHIPPING AGENCIES PVT LTD","SEAWORLD LINE (ASN)","ASR INDIA PVT LTD","AUSTERE LOGISTICS PVT LTD","ALPINE","ASA","AUSTERE LOGISTICS PVT LTD","GLOTTIS","NEW WAY LINES","BALAJI SHIPPING","CHINA NAVIGATION COMPANY PTY","UAFL","BEN LINE","BSS","BILANDER LOGISTICS PVT LTD","BLUE WATER LINES PTE LTD","BLUE WORLD SHIPPING AGENCIES PVT LTD","BLUEMARLIN CONTAINER LINE PRIVATE LIMITED","BLUEMARLIN CONTAINER LINE PVT LTD","BOX TRADE PTE LTD","AAHIL SHIPPING AND LOGISTICS PVT LTD","BOXPARK TERMINALS CO","BRILLIANT SHIPPING SERVICES PVT LTD","BRINE","BALAJI SHIPPING","ALLIANCE CONTAINER LINE LLP.","BURAQ SHIPPING LINE LLP","CAPE OCEAN SHIPPING INDIA PVT LTD.","CARAVEL","CARE CONTAINER LINES PRIVATE LIMITED","CARGO MARKETING INTERNATIONAL PRIVATE LIMITED","CASTO SHIPPING","CHAKIAT AGENCIES PVT LTD","CHARBHUJA CARGO HANDLERS","CHINA UNITED LINES LTD.","CSP","CMA CGM DPD","ANL LINE","CMA-CGM","DELMAS","CGL","PTS","TRANSVISION SHIPPING PVT LTD","ECL","ARIES SHIPPING AND LOGISTICS","CONOCEAN12 AGENCIES","CORDELIA CONTAINER SHIPPING LINE PRIVATE LIMITED","CORVETTE SHIPPING PVT LTD","COSCO","COSCO SHIPPING LINES (INDIA) PRIVATE LIMITED","COSCO","CROSSOVER TANK CONTAINERS (I) PRIVATE LIMITED","CSAV","COSCO SHIPPING LINES (INDIA) PRIVATE LIMITED","CSE","NIPPON YUSEN KAISHA LINES","DAHNAY LOGISTICS PRIVATE LIMITED","MASTER LOGITECH PVT LTD","ASIATIC CONTAINER LINES (I) PVT LD","DENLINE","DESTINY SHIPPING AGENCY PVT LTD","DIAMOND MERITIME AGENCY","DIAMOND MERITIME AGENCY","DDI","DOMESTIC","DOMESTICIMPORT","DUMMY","E SHIP GLOBAL LOGISTICS","ECON LINE","ECON LINE","E LINE","EMS","FREESEAS","SEA EXPRESS","EMINENT DPD","EMINENT SHIPPING SERVICES LLP","EMIRATES","ENTRUST SHIPPING SERVICES PRIVATE LIMITED","KOREA MARINE TRANSPORT CO. LTD.","ESSE SHIPPING AND CONTAINER LINES LTD","XTRANS LOGISTICS PRIVATE LIMITED","ETHIOPIAN SHIPING AND LOGISTICS SERVICES ENTERPRISE","EVERGREEN","AAHIL SHIPPING AND LOGISTICS PVT LTD","ECL","SIT","EXCEL SHIPPING AGENCIES","EXCELSIOR SHIPPING LINE LLP","AUSTERE LOGISTICS PVT LTD","EWC","EXPRESSWAY CONTAINER LINE LLP","FAIRFREIGHT LINES PVT LTD","FIRST MARITIME PVT. LTD.","FLORENCE SHIPPING AGENCIES PVT LTD","MITSUI OSK LINES INDIA PVT LTD","PAT","FOURCEE","FCN","FREIGHT CONNECTION INDIA PVT LTD","CARGOGULF LINE","GHUMLI SHIPPING AGENTS PRIVATE LIMITED","GIL DPD","GIL SHIPPING SERVICES PRIVATE LIMITED","SEALEAD (GIL SHIPPING)","GIRICK SHIPPING AGENCIES PVT LTD.","GLACIER","GLOBELINK WW INDIA PVT LTD","WAT","GLPL","BALTIC","GAP","GLPL","GMLLC","VASCO","VGM","GOODWILL INTERMODAL CONTAINERS TRADING PVT LTD","GOODWILL INTERMODAL CONTAINERS TRADING PVT LTD","HSD","HANJIN","HJS","HAPAG","HGL","VSNB","HINDUSTAN CARGO LIMITED","APS","EMKAY","GULF LINE","HMS","HUB & LINKS","HUB AND LINK LOGISTICS PVT LTD","MACTOR LINE(HUB AND LINKS)","MODULE LINE (HMS)","MS SHIPPING AG","IAL","IGM SHIPPING PRIVATE LIMITED","IND","INOX SHIPPING AGENCIES INDIA PVT LTD","INTERASIA DPD","INTERASIA LINES SINGAPORE PTE LTD","INTERGULF SHIPPING LINE PVT LTD","ARC LINE","BAY LINES","IRISL INDIA PRIVATE LIMITED","CCNI","THE SHIPPING CORPORATION OF INDIA LTD","JMK","JML","JOVIAN CONTAINER LINES PVT LTD","K K LOGISTICS","KALASH GLOBAL LOGISTICS PVT LTD","KHYATI SHIPPING SERVICES PVT LTD","KIN SHIP","KING STAR FREIGHT PVT LTD","KMS MARITIME INDIA PRIVATE LIMITED","KMTC DPD","KOREA MARINE TRANSPORT CO. LIMITED.","LANCER","LAUREL NAVIGATION (MAURITIUS) LTD","LLS","ANCHORGE(LIVRO)","ASL","BOX FORCE (LIVRO)","CPI (LVR)","CTI(LIVRO)","EMPIRE (LVR)","LIVRO SHIPPING PVT LTD","MARKHOR(LIVRO)","MKS","OLT","OVERSEAS(LIVRO)","WESTERN FREIGHT(LIVRO)","WFF","SPRINGS SEA SHIPPING LINES AGENTS CO LLC","LONG MERCHANT FREIGHT SERVICES PRIVATE LIMITED","MMT","MAK SHIPPING SERVICES PVT LTD","MARINE BIRDS CONTAINER INDIA LVT LTD","MARINE CONTAINER SERVICES","RCL","MAS SHIPPING","MASTER LOGITECH PVT LTD","MMS","NEW PORT INDIA","MAXICON CONTAINER LINE","ACO LINE","MAXIM SHIPPING PRIVATE LIMITED","VSNB","ST JOHN FREIGHT SYSTEM LTD","MSC","CSCL","TIMES CHARTERING PVT LTD","LINEA MESSINA","MGR","MIML","MILAHA INTERGRATED MARITIME AND LOGISTICS W.L.L.","MILLENIUM MARINE INTERNATIONAL","MISC","MITSUI OSK LINES INDIA PVT LTD","MLH SHIPPING AGENCY INDIA PVT LTD","MLI LOGISTICS INDIA PVT LTD","MLI LOGISTICS INDIA PVT LTD","MONTER SHIPPING AND LOGISTICS INDIA PRIVATE LIMITED","MOONSTAR LINES PVT LTD","MSA LINE","MSC DPD","MUSKAN CONTAINER LINES PVT LTD","N STAR","NAVIO SHIPPING PVT LTD","NAVIS SHIPPING INDIA PVT LTD.","NCL","NERIDA SHIPPING PRIVATE LIMITED","NSL (KARTEN)","SMARTBOX (NSL)","NEXUS CONTAINER LINE PRIVATE LIMITED","NHK CONTAINER LINE LLP","BLPL SINGAPORE PTE LTD","NOVEL","NIPPON YUSEN KAISHA LINES","FESCO INTEGRATED","NIL(OASIS SHIPPING)","TSL","ONE LINE","OCEANAXIS CONTAINER LINES","OMM","OEL EXPRESS INDIA PVT LTD","OMEGA LINERS (INDIA) PVT LTD","HAWK(OMEGA)","INOX(OMEGA)","ONE LINE DPD","OAI","OPAL ASIA","GOSS","OPD","TASL","ORBIT CONTAINER SERVICES PVT LTD","LMT","OOCL","ORIENT SHIP AGENCY","OSL","SPREY SHIPPING","PAN ASIA LINE","PANGLOBE SHIPPING SERVICES PRIVATE LIMITED","PLL","PARAMOUNT SEALINK PRIVATE LIMITED","PSP","CEEKAY","DELMAS","LMT","PAREKH MARINE AGENCIES PVT. LTD","SINOKOR MERCHANT MARINE CO LTD","PARSHURAM BHIKAJI LOGISTICS PVT LTD","INTERGULF SHIPPING LINE PVT LTD","PCL","PIL INDIA PRIVATE LIMITED","MALAYSIA SHIPPING CORPRATION SENDIRIAN BERHAD","PACIFIC INTERNATIONAL LINES","PTS","BLUE WATER LINES PTE LTD","MILAHA INTERNATIONAL MARITIME LLC","PEK(POSEIDON)","PSD","QATAR NAVIGATION","PMD","PSH","PRO","HDS","PRUDENTIAL LINE","RRS","ATS","MCL","WWW","PRO","RVH","RAS","MAXX SERVICES","RR SHIPPING PVT LTD","RRS","RCL","S M CONTAINER LINES PVT LTD","MAAS","SABARI CONTAINER TERMINAL PVT LTD","SAFFRON CONTAINER","SAFRON CONTAINER LINES INDIA PVT LTD","SAI SHIPPING CO PVT LTD","ETHIOPIAN SHIPING AND LOGISTICS SERVICES ENTERPRISE","SAMSARA SHIPPING PRIVATE LIMITED","SAMUDERA SHIPPING LINE (INDIA) PVT LTD","SANCOLINE OVERSEAS PVT LTD","SARANG MARITIME LOGISTICS PVT LTD","SARJAK","SCP","SLL","SC LINES SHIPPING AND LOGISTICS PVT LTD","SEA CARE SHIPPING PVT LTD","SEA CROSS SHIPPING LLP","SEAHAWK","SEA LLOYD SHIPPING LINES PRIVATE LIMITED","SEA MARINE LOGISTICS PVT LTD","SEA MARINE LOGISTICS PVT LTD (SLP)","DAL","QATAR NAVIGATION","RCL","ASYAD","CEEKAY","HAMBURG SUD","HYUNDAI LINE","OMAN CONTAINER LINES","SEAGLE SHIPPING AGENCIES","ASCENT GLOBAL SHIPPING PRIVATE LIMITED","SEAHAWK LOGISTICS PRIVATE LIMITED","SEAHORSE SHIP AGENCIES PVT LTD","SARJAK","MAXICON CONTAINER LINE","MCL","SEEFAR SHIPPING PVT LTD","SEGMENT SHIPPING AGENCIES PVT LTD","SHAL SEA SHIPPING LLC","SHARP LOGISTICS PVT LTD","RELAY SHIPPING(SRL)","SRSL","SLR","SLR","SINOKOR INDIA PCT LTD","SKYLARK CONTAINER LINES LLP","SMARTBOXX LINE","SP CONTAINER LINE PVT LTD","SPARCON LINES PVT LTD","SRS TRADELOGIXS PRIVATE LIMITED","STAR LINE SHIPPING","BLUEPETER SHIPPING PVT LTD","SUNSTAR SHIPPING SERVICES","OSS","SWEN","NCL","SUPER TERRA SDN BHD","SWIFT LINE","TS LINE","TSH","TAN LINE","ECL","TPC","TIME GLOBAL SHIPPING VENTURS PVT LTD","TIMES CHARTERING PVT LTD","TLPL INTERGRATED SHIPPING SERVICES PVT LTD","TLPL SHIPPING PVT. LTD.","TAS","SUL","TRANS GLOBE LOGISTICS","VOS","TRANSLINER MARITIME PVT LTD","TRANSLINER MARITIME PVT LTD","TRANSNATIONAL SHIPPING INDIA PVT LTD","TRANSNATIONAL SHIPPING INDIA PVT LTD","OSL","TRANSVISION SHIPPING PVT LTD","TRANSVOY LOGISTICS INDIA LIMITED","BLPL SINGAPORE PTE LTD","MBF(TRANSWORLD GLOBAL)","MITSUI OSK LINES INDIA PVT LTD","BLPL SINGAPORE PTE LTD","LINEA MESSINA","TTPL","TRI","TRISTAR LOGISTICS (INDIA) PVT LTD","UNIAO INTERNATIONAL GENERAL TRADING LLC","UNICON LOGISTICS INDIA PVT LTD","UNICORN LOGISTICS INDIA PVT LTD","AVANA","UNF(UNIFEEDER)","UASC","K LINE","UNITED LINER AGENCIES OF INDIA PVT LTD","UNITED LINER SHIPPING SERVICES LLP","V S AND B DOMESTIC CONTAINER SOLUTIONS PVT LTD","VCL","VISTAR SHIPPING LLC","WAN HAI LINES LIMITED","WAM","ACE(WINASIA)","HALLMARK LINE","PROJECT LINE","VOLGA LINE (WINASIA)","WAM","WIND AND WAVES SHIPPING PRIVATE LIMITED","OSL","WOM(WINOCEAN)","ACL","ALLIGATOR LINE","CAPITAL(WINWIN)","CPI ( WINWIN )","EMA LINE(WINWIN)","INOVI LINE (WINWIN)","MER LINE (WINWIN)","MERIDIAN LINE","OSL","PROJECT LINE","SEAHORSE WINWIN LINE","SEAWORLD LINE","SHIPNER(WINWIN)","VMR(WINWIN)","WFFPL LINE (WINWIN)","WIN WIN LINE","WINWIN MARITIME PVT LTD","ACL","HAWK LINE","MERIDIAN LINE","OSL","WIN WIN LINE","WINWIN MARITIME PVT LTD","YANG MING LINE","YMN SHIPPING","ZIM LINE","Z LINE","ZWF","LINE","MAERSK","SAFMARINE","A PLUS","A S R LINERS INDIA PRIVATE LIMITED","ARS","AAHIL","BTC","SSH","SARANG MARITIME LOGISTICS PVT LTD","ABLE SHIPPING","EXODUS","INDUS CONTAINER LINES PRIVATE LIMITED","NOMA","TRANCEMARINE","AEGON SHIPPING INDIA PVT LTD","AFLOAT","AFLOAT FREIGHT","ASM LINE","DEN LINE","AIYER SHIPPING AGENCY PVT. LTD.","SFS LINE","BALAJI LINE","ALISPED INDIA PVT LTD","ALLIANCE CONTAINER LINE LLP","AOCL","ALX","AMAN CONTRANS INDIA PRIVATE LIMITED","ANL SINGAPORE PTE LTD","AMERICAN PRESIDENT LINE","CONOCEAN12 AGENCIES INDIA PVT LTD","OMEGA LINERS (INDIA) PVT. LTD.","ARMITA INDIA SHIPPING PVT LTD","IRISL","ARVIA SHIPPING PRIVATE LIMITED","ASIATIC","ASL","ASN","ATHENA(ASN)","BRIGHT LINE (ASN)","LEGEND LINE(ASN)","MODERN","MORDERN(ASN)","OCEAN LINE (ASN)","SEAWORLD (ASN)","ASR INDIA PVT LTD","ASR INDIA PVT LTD","ATL SHIPPING AND LOGISTIC","AUSTERE LOGISTICS PVT LTD","AUSTERE SHIPPING AND LOGISTICS PRIVATE LIMITED","BSL","TSA UNIFEEDER","INTERMARK","CHINA NAVIGATION COMPANY PTY","UNITED AFRICA FEEDER LINES","BLA","CHINA NAVIGATION COMPANY PTY","UNITED AFRICA FEEDER LINES","BSS","BILANDER LOGISTICS PRIVATE LIMITED","BLESS MARITIME","BLPL SINGAPORE PTE LTD","BLUE WORLD SHIPPING AGENCIES PVT LTD.","BWS","BML","BTC","BOXTRADE","BRILLIANT SHIPPING SERVICES PVT . LTD","BRINE MARITIME INDIA PRIVATE LIMITED","BALAJI LINE","BULKISO TAINER LOGISTICS INDIA PRIVATE LIMITED","ASJS LOGISTICAL SERVICES PRIVATE LIMITED","CAPE OCEAN SHIPPING INDIA PVT LTD","COSTAL CCL (CAPE OCEAN)","GENESIS CHEMICAL(CAPE OCEAN)","NAUTICA LINE","OLIVE LINE (CAPE OCEAN)","PASSARGAD UNITED SEA SHIPPING","SCENERY SHIPPING(CAPE OCEAN)","SPL(CAPE OCEAN)","VOLANS","CARAVEL LOGISTICS PVT LTD","CAS","EXCELSIOR SHIPPING LINE LLP","MOON STAR LINES PRIVATE LIMITED","CGL LOGISTICS PVT LTD","GSR SHIPPING PVT LTD","CHAKIAT","CCH","ISP","CSP","PROJECT LINE","CMA CGM DPD","CMA CGM","CONOCEAN12 AGENCIES INDIA PVT LTD","MAK CONTAINER LINE","CORDELIA CONTAINER SHIPPING LINE","CCS","COSCO INDIA SHIPPING PVT LTD","CTC","CSAV","DAHNAY LINE","MASTER LOGITECH PVT. LTD.","MMS","OLI","TGL","COSCO INDIA SHIPPING PVT LTD","DECCAN","DAG","DEMCO LINE","DENLINE","DIAMOND MERITIME AGENCY","DOMESTIC","DOMESTICIMPORT","E SHIP GLOBAL","E SHIP GLOBAL LOGISTICS","EZ LINERS","ECON LINE","ECONSHIP TECH PRIVATE LIMITED.","E LINE(EMS)","EFFICIENT MARINE SERVICES LLP","FREESEAS","MLH(EMS)","SEA EXPRESS (EMS)","SJL(EMS)","EIS EXIM INT","ELITE OCEAN LINE PVT LTD","EMT","DOEHLE DANAUTIC","ESA","ACE","ENS","EQUINOX SEATRADE PVT. LTD.","ESSE SHIPPING AND CONTAINER LINES LIMITED","ESTANICHA TRANSPACIFIC PRIVATE LIMITED","HIND FREIGHT SERVICES PVT LTD","ESTANICHA TRANSPACIFIC PRIVATE LIMITED","EBL","EMC","ABS (ECL) LINE","ABS LINE (ECL)","APSL LINE","BARCO FREIGHT","CIRCLE SHIPPING","DESTINY SHIPPING SERVICE","EVERSHINE CONTAINER LINE PVT LTD","IGM SHIPPING PRIVATE LIMITED","MOVEX (ECL)","OSPREY SHIPPING PVT LTD","PAN GLOBE(ECL)","PCL SHIPPING","PRINCIPAL SHIPPING LINE","SMC","TAURUS(ECL)","TIME GLOBAL SHIPPING LLC","VISION CONTAINER LINE PVT LTD","SIT","EXCEL SHIPPING AGENCIES","EXCELSIOR SHIPPING LINE LLP","EWC","EXPRESSWAY CONTAINER LINE LLP","FFL","FAZ","FESCO OCEAN MANAGEMENT LTD","FIR","PAT","FOURCEE","ARC","FCN","GAC","HOYER LINE","GALEON","GALLEON","GSA","SEA XPRESS","VERTEX","GIL SHIPPING","SEALEAD(GIL SHIPPING)","VOLTA","GSA","GSL","GLOBELINK WW INDIA PVT LTD","WAT","GLPL","BALTIC","GAP","GLPL","GMLLC","GMPL","VASCO","GOODWILL","GOODWILL INTERMODAL SHIPPING PVT LTD","GSR SHIPPING PVT LTD","HAMBURG SUD AMERICAN ISCHE DAMPFSCH.","HAMBURG SUD","HANJIN SHIPPING","HAPAG LLOYD AKTIENGESELLSCHAFT","HARVARD GLOBAL LOGISTICS LIMITED","HLP","MSC","HMM INDIA PVT LTD","CAPE LINE","EMKAY","HUB & LINKS LOGISTICS (I) PVT LTD","HUB AND LINKS LOGISTICS INDIA PVT LTD","MACTER LINE(HUB AND LINKS LOGISTICS INDIA PRIVATE LIMITED)","MODERN","MOON STAR LINES PRIVATE LIMITED","MOONSHINE LINE","SHAH AZIZ (HUB AND LINK)","HVS","IAL","IGM SHIPPING PRIVATE LIMITED","IGM SHIPPING PVT. LTD.","SAI SHIPPING CO.(P)LTD","BABAJI SHIVRAM CLEARING AND CARRIERS PVT.LTD.","AFLOAT","INDU SHIPPING LINE LLP","INOX SHIPPING AGENCIES INDIA PVT LTD","INSPIRE CONTAINER LINE","INTERASIA LINES SINGAPORE PTE LTD","INTERGULF SHIPPING LINE PVT LTD","BAY LINES","INTERMARK SHIPPING AGENCIES PVT.LTD.","IRISL","ISS SHIPPING INDIA PRIVATE LIMITED","JMB","JMS","THE SHIPPING CORPORATION OF INDIA","JAIVAL SHIPPING SOLUTIONS","JMK","JODAC SHIPPING PRIVATE LIMITED","JSL","JOVIAN CONTAINER LINES PVT LTD","KKL","K LINE","KALASH GLOBAL LOGISTICS PRIVATE LIMITED","KALASH GLOBAL LOGISTISTICS PVT LTD","KALASH GLOBAL LOGISTISTICS PVT LTD","KHYATI SHIPPING SERVICES PVT LTD","KING STAR FREIGHT PVT. LTD.","KINSHIP","SEA EXPRESS","KMS MARITIME INDIA PRIVATE LIMITED","KMT","KMT","KOREA MARINE TRANSPORT CO. LTD.","LANCER","LEL","LEGEND LOGISTICS","LEGEND SHIPPING AGENCIES","ANCHORAGE(LVR)","BOX FORCE(LVR)","BURRAQ(LVR)","CARGO PLAN(LVR)","CTI(LVR)","ELITE(LVR)","EMPIRE(LVR)","LIVRO SHIPPING PVT LTD","MARKHOR(LVR)","OVERSEAS(LVR)","RAVIAN(LVR)","SEAHORSE(LVR)","SHIPNER(LVR)","LOGENIX INTERNATIONAL","SPRINGS SEA SHIPPING LINES AGENTS CO LLC","LONG MERCHANT","LOTUS CONTAINERS SHIPPING SERVICES LLC","MAK CONTAINER LINE","MAAS CONTAINER LINE","DOLPHIN SHIPPING LINE U.K LTD","MAJESTIC MARITIME PRIVATE LIMITED.","MAK","YANG MING LINE","MARITIME SERVICES PVT LTD","MAS SHIPPING AGENCIES PRIVATE LIMITED","MMS","MMS","MAXICON SHIPPING AGENCIES PVT LTD","MAXIM SHIPPING PRIVATE LIMITED","GLOBAL CORP LOGISTICS LLC","MBK LOGISTIX PRIVATE LIMITED","MSC","MCT","CSCL","LINEA MESSINA","MGR CONTAINER LINE INDIA PVT LTD.","MILAHA INTERGRATED MARITIME AND LOGISTICS WLL","MMI","MISC BERHAD","MITSUI OSK LINES INDIA PVT LTD","MLI","MONTER SHIPPING AND LOGISTICS INDIA PVT LTD","MOON STAR LINES PRIVATE LIMITED","IRISL","MSA","MSA LINE","MSC DPD","MUSKAN CONTAINER LINES PVT LTD","N STAR","NAVDEEP SHIPPING PRIVATE LIMITED","NAVIO SHIPPING PVT LTD","NAVIS","NEPTUNE CONTAINER LINES","NERIDA SHIPPING PVT LTD","NH SHIPPING PVT LTD","NHK CONTAINER LINE LLP","NLS AGENCY (INDIA) PVT.LTD.","NBS","NOBLE SHIPPING PVT LTD","XXXXXNOVEL LINES","INTER (NOVEL)","NOVEL LINE AND LOGISTICS PVT LTD","NIPPON YUSEN KAISHA LINES","FOS","NIL(OASIS)","NILE DUTCH AFRICA LINE B.V","TSL","OSO","OCEANAXIS CONTAINER LINES","OCEANMASTERS MARINE SERVICES PVT LTD","BLUEPETER SHIPPING PRIVATE LIMITED","INOX(OMEGA)","OLI","OMEGA LINERS (INDIA) PVT. LTD.","ONE (OCEAN NETWORK EXPRESS) LINE INDIA PVT LTD","ONE LINE","OPAL ASIA","PAL","GOSS","OPD","LMT","OOCL","ORIENT SHIP AGENCY PVT LTD","ORIENT SHIP AGENCY PVT LTD","OSA","OSL","OSL SHIPPING AGENCIES (INDIA) PVT. LTD","OSPREY SHIPPING PVT LTD","PAN ASIA LINE","PAN LLOYD LINES","PARAMOUNT SEALINK PRIVATE LIMITED","CEEKAY","DELMAS","HMM INDIA PVT LTD","PAREKH MARINE AGENCIES PVT. LTD.","PARSHURAM BHIKAJI LOGISTICS PVT LTD","PCL","PERMA CONTAINER U.K LINE","PHOENIX ENTERPRISES","PIL INDIA PVT. LTD.","MSB","PACIFIC INTERNATIONAL LINES","PTS","BLUE WATER LINES","MIM","PSD","QATAR NAVIGATION","PMD","PSH","OEL","TPC","WILHELMSEN MARITIME SERVICES PVT LTD","PRO","HDS","PRUDENTIAL LINE","RADIANT LINE","RAMA VESSEL HANDLERS PVT.LTD.","RAS","RELIABLE SHIPPING SERVICES","RELIANCE","SHARP LOGISTICS PRIVATE LIMITED","RR SHIPPING PVT LTD","SMC","SAARTHEE SHIPPING COMPANY LINE","SCL","SAI SHIPPING CO.(P)LTD","SAI SHIPPING CO.(P)LTD","ETHIOPINAN SHIPPING AND LOGISTICS ENT","HEUNG A LINE CO. LTD","HOYER GLOBAL TRANSPORT B V","SAMUDERA SHIPPING","SSL","SANCO","SAR TRANSPORT SYSTEMS PRIVATE LIMITED","SARANG MARITIME LOGISTICS PVT LTD","SARJAK","SATKAR CONTAINER LINE PVT LTD","SC LINE","SCLINES SHIPPING AND LOGISTICS PVT LTD","SCR","SEA CARE SHIPPING PVT LTD","SEA CARE SHIPPING PVT LTD","SEA EXPRESS SHIPPING AGENCIES PVT LTD","RAS","SGL","SEA HAWK LINES PVT LTD","SHAL SEA SHIPPING LLC","SEAHAWK LOGISTICS PVT LTD","SEA LLOYD SHIPPING LINES PRIVATE LIMITED","SEA MARINE LOGISTICS PVT LTD","SML","DAL","MARITIME SERVICES PVT LTD","QNL","RCF","ASYAD LINE","HYUNDAI","HAMBURG SUD","HMM INDIA PVT LTD","OMAN CONTAINER LINES","OMN","SEACROSS SHIPPING LLP","SEAGLE","SEAHAWK LOGISTICS PVT LTD","ASIA LINE SHIPPING HK LTD","ASIAWISE SHIPPING LINE","ASJS LINE","BOATLINK SHIPPING","CGL LINE (SSA)","CHINA UNITED LINES","GNL LINE","LANCIA(SSA)","MALDIVES STATE SHIPPING (SSA)","MTT SHIPPING SDN BHD","OCEAN STAR LINE","PROJECT LINE(SSA)","SEAHORSE SHIP AGENCIES PRIVATE LIMITED","TIMELOG SHIPPING","WESTERN FREIGHT FORWARDING SHIPPING","SARJAK","SES","SEASPEED CONTAINER LINE","SEASPEED LINE","SEATRANS","MAXICON SHIPPING AGENCIES PVT LTD","SEGMENT SHIPPING AGENCIES PVT LTD","SHAL SEA SHIPPING LLC","SHARP LOGISTICS PRIVATE LIMITED","BALAJI LINE","SHREYAS RELAY SYSTEMS LTD","SILMAR LOGISTICS PRIVATE LIMITED","SIMA MARINE INDIA PVT LTD","SINOKOR MERCHANT MARINE CO LTD","SKYBLISS","SKYCON","SKYLARK","SMERA LINES","SO CONTAINER LINE PVT LTD","SPARXX MARITIME AND LOGISTICS PVT LTD","SRS TRADELOGIXS PRIVATE LIMITED","STAR LINE SHIPPING","STA","SUL","MGR CONTAINER LINE INDIA PVT LTD.","SUNDERSONS LOGISTICS PVT LTD","SUNSTAR SHIPPING SERVICES","SWIFT LINE","SWIFT LINE","TSH LINE","TSL","LOGENIX INTERNATIONAL","TANLINE PRIVATE LIMITED","TCI","OEL","TPC","WILHELMSEN MARITIME SERVICES PVT LTD","TIMES CONTAINER LINE","TLPL","TLPL","WSL","TRANCECARE LOGISTICS PRIVATE LIMITED","TAS","OLI","SUL","TGL","VOS","TGL","TRANSLINER MARITIME PVT LTD","TRANSNATIONAL SHIPPING INDIA PVT LTD","TRANSVISION SHIPPING PVT LTD","BLPL SINGAPORE PTE LTD","MITSUI OSK LINES INDIA PVT LTD","BLPL SINGAPORE PTE LTD","NLS AGENCY (INDIA) PVT.LTD.","LINEA MESSINA","TLL","TRISTAR LOGISTICS (INDIA) PVT LTD","TRISTAR LOGISTICS INDIA PVT LTD","UNICON LOGISTICS (INDIA) PRIVATE LIMITED","TRANSWORLD LOGISTICS","TSA UNIFEEDER","UNIFEEDER","UNITED ARAB SHIPPING CO","K LINE","AA SHIPPING (ULA)","AAS","CARE LINE","GLA(ULA)","PMD","SSL","TAURUS(ULA)","TRANSAFE LINE","ULS","VERTEX LINE","ASN","V CAN LOGISTICS SOLUTION PVT LTD","VSB","ELITE OCEAN LINE PVT LTD","EVERSHINE CONTAINER LINE PVT LTD","VISION CONTAINER LINE PVT LTD","WAN HAI LINES LIMITED","WSL","DENIZ(WAM)","HALLMARK LINE","OWN LINE(WAM)","PROJECT LINE","SYNERGY (WINASIA)","WAM","WINASIA MARITIME PRIVATE LIMITED","WIND AND WAVES SHIPING PVT LTD","WINOCEAN MARITIME","ACE LINE","AIM LINE WML","ALLIED CONTAINER LINE","ALLIGATOR LINE","BALTIC","BOX FORCE(WINWIN)","C TRACKS GLOBAL","CAPITAL ONE LINE","CARGO PLAN INTERNATIONAL","CARTER LINE","CSL LINE","ELITE","EMA","EVC","FULL STAR LINE","HAWK LINE","INOVI LINE(WML)","LEGEND LINE(WINWIN)","LG LINE(WML)","MARKHOR LINE","MER LINE (WINWIN)","MERIDIAN LINE","OSL WINWIN","RISHI KIRAN LOGISTIC PVT LTD","SHIPNER LINE WINWIN","SK LINE","SKY LINE","SPIRIT(WML)","UNITED OCEAN EXPRESS LINES","VMR LINES LIMITED","WFFSL(WML)","WINWIN","YSL WINWIN","HAWK LINE","OSL WINWIN","SKY LINE","WAT","WINWIN","WINWIN MARITIME PVT LTD","ETP XTRANS","XTRANS LOGISTICS PRIVATE LIMITED","GOSS","YANG MING LINE","YMN SHIPPING","STAR SHIPPING SERVICES INDIA PVT. LTD.","ZIM LINE","ZIM WORLD FREIGHT","ZOD","LINE","ABLE SHIPPING AGENCIES (I) PVT LTD","ADITYA ENTERPRISES","ADMEC","AEGON SHIPPING INDIA PRIVATE LIMITED","AFLOAT CONTAINER LINES INDIA PRIVATE LIMITED","AFRAMAX LOGISTICS","AISSA MARITIME PVT LTD","AIYER SHIPPING AGENCY PVT LTD","ALBATROSS LEASE CONTAINER","ALBATROSS SHIPPING LTD","ALLIANCE CONTAINER LINE LLP","ALX SHIPPING AGENCIES INDIA PRIVATE LIMITED","AMBER ENTERPRISES","CMA CGM","CMA CGM","AP LOGISTICS INDIA PVT LTD","APL INDIA (P) LTD.","APL INDIA (P) LTD.","ARC LINE C/O. FREIGHT CONNECTION INDIA PVT. LTD.","ASL SHIPPING AND LOGISTICS INDIA PVT LTD","ASR INDIA PVT LTD","ASTER CARGO PRIVATE LIMITED","AVANA GLOBAL FZCO","BABAJI SHIV RAM","BALAJI SHIPPING LINE FZCO AGENT SHREYAS RELAY SYSTEM LIMITED","BAY LINES","BAY CONTAINER TERMINAL PVT.LTD.","BEN LINE AGENCIES (INDIA) PVT LTD","BHAVANI SHIPPING SERVICES PVT LTD","BHAWANI TRANS SOLUTIONS","BILANDER LOGISTICS PVT LTD","TRANSWORLD GLOBAL LOGISTICS SOLUTIONS (INDIA) PVT LTD","BLUE WORLD SHIPPING AGENCIES PVT LTD","BLUEMARLIN CONTAINER LINE PRIVATE LIMITED","BOXCO LOGISTICS INDIA PVT LTD","BOXCOWORLD","BOXPARK TERMINAL CO","BOXTRANS SHIPPING AGENCIES P LTD.","BSL FREIGHT SOLUTIONS PVT LTD.","BUDHIRAJA LEASE CONTAINER","CARAVEL LOGISTICS PVT. LTD.","CARE CONTAINER LINES","CARGOSOL SHIPPING AGENCY PVT LTD","CASTO SHIPPING LINE","CEL LOGISTICS PVT LTD","CHARBHUJA CARGO HANDLERS","CLIFFLINE SHIPPING INDIA PRIVATE LIMITED","CMA CGM","CMA CGM","COMPANIA CHILENA DE NAVEGACION INTEROCEANICA S.A.","CONTAINER CARRIERS INTERNATIONALS PVT LTD","CONTFREIGHT SHIPPING AGENCY (INDIA) PVT LTD","CORDELIA CONTAINER SHIPPING LINE PRIVATE LIMITED","CHINA OCEAN SHIPPING (GROUP) COMPANY (COSCO GROUP)","CROSS LINK SHIPPING PVT. LTD.","COMPAÑÍA SUD AMERICANA DE VAPORES","CU LINES PTE. LTD I/O SEAHORSE SHIP AGENCIES PVT. LTD.","DAHNAY LOGISTICS PRIVATE LIMITED","DAYA EXPORTS","DECCAN TRANSCON SHIPPING LLP","DELMAS","DELPHIN GLOBAL SERVICES","DOLPHIN INC","DV RUBBER INDUSTRIES PRIVATE LIMITED","E-WAY ALLIANCE INDIA PRIVATE LIMITED","EASY SHIPPING INDIA PRIVATE LIMITED","ECONSHIPIN MARINE PVT LTD","ECONSHIP TECH PRIVATE LIMITED","EMINENT SHIPPING SERVICES LLP","EMIRATES SHIPPING LINES","EMU LINES PRIVATE LIMITED","ENTRUST SHIPPING LINE","EVERGREEN LINE","EVERSHINE CONTAINER LINE PVT. LTD","EXPRESSWAY SHIPPING (I) PVT. LTD.","FABKING CONTAINERS PVT LTD","FAIRFREIGHT LINES PRIVATE LIMITED","SEASSPEED CONTAINER LINES PVT LTD","FIRST MARITIME PVT LTD","FORBES CONTAINER LINE PTE LTD","ARC LINE","BAY LINES","FREIGHT CONNECTION INDIA PVT. LTD.","GAC SHIPPING (INDIA) PVT. LTD","GHUMLI SHIPPING AGENTS PRIVATE LIMITED","GIL SHIPPING SERVICES PVT LTD","GOLD STAR LINE","GOLD STAR LINE","GOLDEN HORN CONTAINERS SERVICE","GOODRICH LOGISTICS PRIVATE LIMITED","GOODRICH MARITIME LTD","GREENWICH MERIDIAN LOGISTICS (I) PVT. LTD.","HAMBURG SUDAMERIKANISCHE DAMPFSCHIFFFAHRTS GESELLSCHAFT APS & CO KG","HAMBURG SUD","HAMBURG SUD","HAMBURG SUD","HAMBURG SUD","HAMBURG SUD","HANJIN SHIPPING","HLAG","HARSHVARDHAN INTERNATIONAL","HINDUSTAN CARGO LTD","HMA AGRO INDUSTRIES LIMITED","HMM SHIPPING INDIA PRIVATE LIMITED","HUB & LINKS LOGISTICS INDIA PVT LTD","HYUNDAI MARCHANT MARINE CO. LTD","IAL CONTAINER LINE (UK) LIMITED","BABAJI SHIV RAM","BABAJI SHIV RAM","INDO CARRIERS","INDU SHIPPING LINE LLP","INDUS CONTAINER LINE","INEXT","INOX SHIPPING AGENCIES INDIA PVT LTD","INTERGULF SHIPPING LINE PRIVATE LIMITED","J. M. BAXI & CO","JAMES PTE LTD","JBM LOGISTICS SERVICES YARD","JOVIAN CONTAINER LINES PVT LTD","JYOTI SALES","K LINE","KALASH GLOBAL LOGISTICS PVT LTD","KING STAR FREIGHT PRIVATE LIMITED","KOREA MARINE TRANSPORT CO. LTD","LANCER CONTAINER LINE PVT LTD","LANCER CONTAINER LINES PVT LTD","LASCO SHIPPING CO PVT LTD","LAUREL NAVIGATION LTD","LAUREL NAVIGATION MAURITIUS LTD.","LINE_UNKNOWN","LANCER CONTAINER LINE PVT LTD","LODESTAR CONTAINER LINES PVT LTD","LODESTAR CONTAINER LINES PVT LTD","LODESTAR CONTAINER LINES PVT LTD","LOGISTICS SERVICES PVT LTD","STX PAN OCEAN LTD","ACE GLOBAL LINE","MAERSK A/S A/C HAMBURG SUD","MAI LINE","MAI LINE","MAGIC OVERSEAS","MAJESTIC MARITIME PRIVATE LIMITED","MAJHA TRANSPORT PVT LTD","MAK SHIPPING SERVICES PVT. LTD.","MAP LOGISTICS PVT LTD","MARI TIME SERVICES PVT LTD","MARINE CONTAINER SERVICES (I) PVT. LTD.","MARINESTARS CONTAINER LINE","MAS SHIPPING AGENCIES PVT LTD","MASTER LOGITECH PRIVATE LIMITED","MASTER MARINE SERVICES PRIVATE LIMITED","MAXICON CONTAINER LINE","MERCHANT SHIPPER SERVICES","MESSINA LINE","MERINO","METRO EXIM","METRO LOGISTICS","MGR CONTAINER LINE INDIA PVT.LTD.","MISC BERHAD","MITSUI OSK LINES","MLI LOGISTICS INDIA PRIVATE LIMITED","MONTER SHIPPING & LOGISTICS INDIA PRIVATE LIMITED","MOSER BAER LEASED CONTAINER","MSA SHIPPING PRIVATE LIMITED","MEDITERRANEAN SHIPPING COMPANY","MEDITERRANEAN SHIPPING COMPANY","MUSKAN CONTAINER LINES PVT LTD","NAVIO SHIPPING PRIVATE LIMITED","NEPTUNE CONTAINER LINE AND LOGISTICS PVT LTD","NERIDA SHIPPING PRIVATE LIMITED","NEWPORT INDIA PVT. LTD.","NOBLE SHIPPING PVT LTD","FOURCEE INFRASTRUCTURE LTD","NOVEL LINES & LOGISTICS PVT LTD","NIPPON YUSEN KAISHA LINES","OASIS SHIPPING PVT LTD","ONE ( OCEAN NETWORK EXPRESS ) LINE INDIA PVT LTD","OCEANAXIS CONTAINER LINES (I) PVT.LTD","OEL EXPRESS INDIA PRIVATE LIMITED","OM SHAILSHUTA LOGISTICS PVT.LTD","OMEGA SHIPPING AGENCIES PVT LTD","OMEGA SHIPPING AGENCIES PVT. LTD.","OPAL SHIPPING AGENCIES INDIA PVT LTD","OPUS DEI LOGISTICS INDIA PRIVATE LIMITED","ORCHID SHIPPING PVT. LTD.","OOCL (INDIA) PRIVATE LTD","NATIONAL SHIPPING CO OF SAUDI ARABIA","OSL SHIPPING AGENCIES (I) PVT LTD","OSL SHIPPING AGENCIES INDIA PRIVATE LIMITED","PAN ASIA LINE","PAN LLOYD","PARAMOUNT SEALINK PVT LTD","PAREKH MARINE AGENCIES PVT. LTD.","PASWARA","PAVANI LOGISTICS","PERMA CONTAINER U.K LINE","PACIFIC INTERNATIONAL LINES","PLIMSOLL LOGISTICS PVT LTD","PORT TRADE SHIPPING AGENCIES PVT. LTD","POSEIDON SHIPPING AGENCY PRIVATE LIMITED","POSEIDON SHIPPING AGENCY PVT LTD","PRADHAN LOGISTICS","PRT TRADE SHIPPING AGENCIES PVT LTD","R S ISPAT INDUSTRIES","RADIANT MARITIME INDIA PVT LTD ¿ NEW DELHI (INDIA)","RASHI SHIPPING SERVICES PRIVATE LIMITED","RCL FEEDER PTE LTD","RED EAGLE SHIPPING AGENCIES PVT LTD.","RENTACO (OPC) PRIVATE LIMITED","S H A L SEA SHIPPING LLC","S M ENTERPRIZES","SAFMARINE INDIA","SAI SHIPPING CO PVT LTD","HOY","SAR TRANSPORT SYSTEMS PVT LTD","SARANG MARITIME LOGISTICS PVT. LTD","SARJAK CONTAINER LINE PVT LTD","SATKAR LOGISTICS PVT LTD","SEA CARE SHIPPING PVT. LTD.","SEA EXPRESS SHIPPING AGENCIES PVT LTD","SEA GOLD LOGISTICS PRIVATE LIMITED","SEA HAWK LINES PVT LTD","SEA MARINE LOGISTICS PRIVATE LIMITED","TANLINE PRIVATE LIMITED","SEA MARINE SHIPPING AGENCIES","SEA TRADE SHIPPING (INDIA) PVT. LTD.","SEABRIDGE MARINE AGENCIES PVT LTD","SEABRIDGE MARITIME AGENCIES PVT LTD","HAMBURG SUD","SEAHORSE SHIP AGENCIES P LTD.","AMFICO AGENCIES PVT LTD","SEALINK FREIGHT & SHIPPING PVT LTD","SEAPORT LINES (INDIA) PVT. LTD.","SEAWAYS LINER AGENCIES PVT LTD","SEAWORLD SHIPPING & LOGISTICS PVT LTD","SGS","SHANTI INDUSTRIES","SHEELA","SHIKHAR LOGISTICS PVT. LTD.","SHREYAS RELAY SYSTEM LIMITED A/C BALAJI SHIPPING LINE FZCO","SHREYAS RELAY SYSTEMS LTD.","SHRI DAYARAM PLASTIC SCRAP TRADING","SINOKOR MERCHANT MARINE CO LTD","SM LINESS","SMART MARINE SERVICES PRIVATE LIMITED","SP CONTAINER LINE","SPJ CARGO PVT LTD","SSMOMMY INTERNATIONAL PRIVATE LIMITED","STAR LOGISTICS","STELLAR LOGISTICS PVT LTD","A/C SUNDERSON LOGISTICS PVT LTD","SUNSTAR SHIPPING SERVICES","T.S. LINES (INDIA) PVT. LTD","TANLINE PRIVATE LIMITED","THE SHIPPING CORPORATION OF INDIA","THE SHIPPING CORPORATION OF INDIA LTD","TIGER LOGISTICS (INDIA) LIMITED","TLPL INTEGRATED SHIPPING SERVICES PVT LTD","TLPL SHIPPING & LOGISTICS PVT LTD","TOMS SHIPPING PVT.LTD.","TRADE TRACK CARGO","TRANCECARE LOGISTICS PRIVATE LIMITED","TRANCEMARINE AND CONFREIGHT LOGISTICS PRIVATE LIMITED","TRANCEMARINE AND CONFREIGHT LOGISTICS PRIVATE LIMITED","TRANS ASIAN SHIPPING SERVICES PRIVATE LIMITED","TRANS ASIAN SHIPPING SERVICES","TRANS CARE LOGISTICS PVT. LTD.","TRANSAFE GLOBAL LIMITED","TRANSLINER MARITIME PRIVATE LIMITED","TRANSMARINE AGENCIES INDIA PVT LTD","TRANSVISION SHIPPING PVT. LTD.","TRANSWORLD SHIPPING AGENCIES PRIVATE LIMITED","M/S TRANSWORLD SHIPPING & LOGISTICS LTD.","UCL LINE","UFLEX","UNIFEEDER AGENCIES INDIA PRIVATE LIMITED","UNITED ARAB SHIPPING CO","SAMUDERA SHIPPING LINE LIMITED","V BIRD SHIPPING AGENCY PVT LTD","V&B LOGISTICS LEASE CONTAINER","VAC","VICTOR & CO","VISTAR WORLDWIDE LOGISTIC","VS & B DOMESTIC CONTAINER SOLUTIONS PVT LTD","WAN HAI LINES (INDIA) PVT. LTD.","WILHELMSEN MARITIME SERVICES PVT LTD","WINASIA MARITIME PRIVATE LIMITED","WINOCEAN MARITIME PRIVATE LIMITED","WINWIN MARITIME PVT. LTD.","YANG MING LINE","ZIM LINE","ZIM WORLD FREIGHT PVT.LTD","A PLUS BOX SOLUTION","AISSA MARITIME PRIVATE LIMITED","AKULA LOGOISTICS PVT LTD","ALMAS LOGISTICS PVT LTD","AMERICAN PRESIDENT LINES","ANGLO GOLDY SHIPPING & LOGISTICS PVT LTD","ANL LINE","APL CO PTE. LTD.","ARIES MOVERS PRIVATE LIMITED","ASYAD LINE","AUSTERE LOGISTICS PVT LTD","AUSTRALIAN NATIONAL LINE","AVANA LOGISTEK LTD","AVS RIVERLINE CONTAINERS PVT LTD","BALAJI SHIPPING LINE","BEN LINE AGENCIES","BILANDER LOGISTICS PVT. LTD.","BLPL SINGAPORE PTE LIMITED","CARE CONTAINER LINES PVT. LTD.","CEEKAY SHIPPING LINE LLC","CHAKIAT AGENCIES PVT LTD","CHAKIAT SHIPPING SERVICES PVT LTD","CJ DARCL LOGISTICS LTD","CMA CGM AGENCIES (INDIA) PVT. LTD.","CONSOLIDATED SHIPPING LINE ( INDIA ) PVT. LTD.","COSCO SHIPPING LINES (INDIA) PVT. LTD.","DAHNAY LOGISTICS PRIVATE LIMITED","DONG FANG CONTAINERS","EASTERN LINER SHIPPING PRIVATE LIMITED","ECONSHIP MARINE PVT LTD","ECONSHIP TECH PVT LTD","EVERETT INDIA PRIVATE LIMITED","EVERGREEN SHIPPING AGENCY (INDIA) PVT. LTD.","EXPRESSWAY CARGO MOVERS PVT LTD","GLOBAL LOGISTICS SOLUTIONS PVT LTD","GOLD STAR LINE LTD","HAMBURG SUD","HUB & LINK LOGISTICS INDIA PVT LTD","IBAAD LINES PRIVATE LIMITED","INOX SHIPPING AGENCIES INDIA PVT LTD","INTERASIA SHIPPING LINES INDIA PRIVATE LIMITED","INTERGULF SHIPPING LINE PVT. LTD","ISS SHIPPING INDIA PVT LTD","J M BAXI & CO","JAMES MACKINTOSH AND CO PVT LTD","JMR FREIGHT FORWARDER PVT LTD","KMTC LINE","KODI SHIPPING AGENCIES","MAC NELS CONTAINER LINES PVT LTD","MACOLINE SHIPPING PVT LTD","MAERSK LINE INDIA PVT LTD","MAGS IMPEX SHIPPING PVT LTD","MARIANA EXPRESS LINES PRIVATE LIMITED","MARINE CONTAINER SERVICES INDIA PRIVATE LIMITED","MAS SHIPPING AGENCIES PVT LTD","MASTER MARINE SERVICES PVT LTD","MAXICON CONTAINER LINE PTE. LTD.","MAXICON SHIPPING AGENCIES PVT LTD","MBK LOGISTIX PRIVATE LIMITED","MERCHANT SHIPPING SERVICES PRIVATE LTD","MLI LOGISTICS INDIA PRIVATE LIMITED","MONTER SHIPPING & LOGISTICS INDIA PRIVATE LIMITED","MOONSTAR LINES PVT LTD","MSC MEDITARRANEAN SHIPPING C SA","MUSKAN CONTAINER LINES PVT LTD","NAVIO SHIPPING PVT. LTD.","NEPAL SHIPPING LINES","NEPTUNE CONTAINER LINE & LOGISTICS PVT.LTD","NILE DUTCH AFRICA LINE","OASIS SHIPPING PVT LTD","OCEAN NETWORK EXPRESS","OCEAN NETWORK EXPRESS PTE. LTD.","ONE (OCEAN NETWORK EXPRESS) LINE (INDIA) PVT. LTD.","ONE (OCEAN NETWORK EXPRESS) LINE (INDIA) PVT. LTD.","OOCL (INDIA) PVT. LTD","ORIENT OVERSEAS CONTAINER LINE","PARAS PROJECT VENTURES INDIA PVT LTD","PAREKH MARINE AGENCIES PRIVATE LIMITED","PENNON SHIPPING PVT LTD","PERMA SHIPPING LINE INDIA PVT LTD","PERMA SHIPPING LINE INDIA PVT. LTD","PHAROS SHIPPING & OVERSEAS SERVICES PVT LTD","PHAROS SHIPPING AND OVERSEAS SERVICES PRIVATE LIMITED","PIL INDIA PVT. LTD.","PRABHU SHIPPING LINES PRIVATE LIMITED","RADIANT MARITIME INDIA PVT LTD","REGIONAL CONTAINER LINES","RIVER EDGE SHIPPING PVT LTD","S H A L SEA SHIPPING LLC","S M CONTAINER LINES PVT LTD","SAFMARINE","SAMSARA SHIPPING PVT LTD","SAMUDERA SHIPPING LINE (INDIA) PVT LTD","SARJAK CONTAINER LINES PVT LTD","SEA CONSORTIUM SHIPPING INDIA PVT LTD","SEA LLOYD SHIPPING LINES PVT LTD","SEAHORSE SHIP AGENCIES PVT LTD","SEASHIP LOGISTICS PVT. LTD.","SHAIMARINE CONTAINER LINES","SHAL SEA SHIPPING LLC","SHIPPING CORPORATION OF INDIA","SHREYAS RELAY SYSTEMS LTD","SILMAR LOGISTICS","SINOKOR","SUN GLOW FREIGHT & CARGO PVT LTD","SUN GLOW FREIGHT AND CARGO PRIVATE LIMITED","TLPL INTEGRATED SHIPPING SERVICES PVT LTD","TLPL INTEGRATED SHIPPING SERVICES PVT.LTD","TOTAL TRANSPORT SYSTEMS LTD","TRANS ASIAN SHIPPING SERVICES P LTD","TRANSLINER MARITIME PVT LTD","TRANSOCEAN CARGO SERVICES PVT LTD","TRANSVISION SHIPPING PVT LTD","TRANSWORLD GLOBAL LOGISTICS SOLUTIONS (INDIA) PVT. LTD.","TRANSWORLD SHIPPING AGENCIES PVT. LTD.","TRASANVI LOGISTICS PVT. LTD.","UNIFEEDER LINE","UNITED LINER SHIPPING SERVICES LLP","VIVEK FREIGHT AND LOGISTICS PVT LTD","VRUKSHA GLOBAL LOGISTICS","WAN HAI LINES (INDIA) PVT LTD","WIN WIN MARITIME LTD","WORLDGATE EXPRESS LINES INTERNATIONAL PVT LTD","YANG MING LINE ( INDIA ) PVT LTD","Z LINE","ZIM","ZIM WORLD FREIGHT PVT LTD","ZLN (INDIA) PRIVATE LIMITED."};
    ArrayList<String>  containerNos = new ArrayList<String>();



    private Dialog dialog;
    ArrayAdapter<String> adapterItems;
    RecyclerView recyclerView;
    RecycleAdapter adapter;
    ImageView galleryIcon,cameraIcon;
    ArrayList<Uri> uri = new ArrayList<>();
    private static  final int Read_Permission = 101;
    String ImageLink = null;
    private Session session;
    public String selectedLocation;
    ProgressBar progressBarHolder;

    EditText dateTime;
    Uri cam_uri;
    AutoCompleteTextView shippingLineTextView,containerNumberView,activityView,cycleView,conTypeView,conSizeView,locView,surveyorView, conStatusView;
    TextView remark ;
    private GoogleDriveHelper googleDriveHelper;


    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_user_form);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        session = new Session(getApplicationContext());

        googleDriveHelper = new GoogleDriveHelper(this);
        containerNumberView = findViewById(R.id.autoCompleteTextContainerNo);
        dateTime = findViewById(R.id.dateTime);
        activityView  = findViewById(R.id.autoCompleteTextViewActivity);
        cycleView = findViewById(R.id.autoCompleteTextViewCycles);
        conTypeView= findViewById(R.id.autoComTVContTypeList);
        conSizeView= findViewById(R.id.autoComTVContSizeList);
        locView= findViewById(R.id.autoComTVLocationList);
        surveyorView= findViewById(R.id.autoComTVSurveyorNameList);
        conStatusView= findViewById(R.id.autoComTVConStatusList);
        remark = findViewById(R.id.remarkTextView);
        shippingLineTextView = findViewById(R.id.autoComShippingLine);
        progressBarHolder = findViewById(R.id.progressBarHolder);



        galleryIcon = findViewById(R.id.FolderIconImageView);
        cameraIcon = findViewById(R.id.cameraIconImageView);
        recyclerView = findViewById(R.id.recyclerView_Gallery_Images);

        adapter = new RecycleAdapter(uri);
        recyclerView.setLayoutManager(new GridLayoutManager(UserFormActivity.this,2));
        recyclerView.setAdapter(adapter);
        adapter.setOnItemClickListener(new RecycleAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int position) {
                uri.remove(position);
                adapter.notifyItemRemoved(position);
            }
        });

        //Location
        String loc = session.getLoc();
        locView.setText(loc);
        selectedLocation = loc;
        locView.setEnabled(false);
        loadSurveyorList();
        loadActivitiesList();
        loadCyclesList();


        if(ContextCompat.checkSelfPermission(UserFormActivity.this, Manifest.permission.READ_EXTERNAL_STORAGE)
        != PackageManager.PERMISSION_GRANTED)
        {
            ActivityCompat.requestPermissions(UserFormActivity.this,
                    new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},
                    Read_Permission);
        }

        galleryIcon.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent();
                intent.setType("image/*");
                intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true);
                intent.setAction(Intent.ACTION_GET_CONTENT);
                startActivityForResult(Intent.createChooser(intent,"Select Picture"),1);
            }
        });

        cameraIcon.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ContentValues values = new ContentValues();
                values.put(MediaStore.Images.Media.TITLE, "New Picture");
                values.put(MediaStore.Images.Media.DESCRIPTION, "From Camera");
                cam_uri = getApplicationContext().getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);
                Intent cameraIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
                cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT, cam_uri);
                startActivityForResult(cameraIntent,123);
            }
        });

        //Container Number
        Intent intent = getIntent();
        containerNos = intent.getStringArrayListExtra("cno");
        //Master Img
        uri.add(Uri.parse(intent.getStringExtra("masterImg")));
        assert containerNos != null;
        if(!containerNos.isEmpty())
        {
            containerNumberView.setText(containerNos.get(0));
        }

        //Time
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss a");
        LocalDateTime now = LocalDateTime.now(ZoneId.of("Asia/Kolkata"));
        dateTime.setText(dtf.format(now));
        dateTime.setEnabled(false);

        //Container Number
        String[] cnos = new String[containerNos.size()];
        cnos = containerNos.toArray(cnos);
        setDropdowns(containerNumberView, cnos);



        //Shipping Line
        setDropdowns(shippingLineTextView,shippingLine);

        //Container Type
        setDropdowns(conTypeView,containerType);

        //Container Size
        setDropdowns(conSizeView,containerSize);

        //Locations
        setDropdowns(locView,locations);

        //Container Status
        setDropdowns(conStatusView,containerStatus);

        containerNumberView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                String item = adapterView.getItemAtPosition(position).toString();
                containerNumberView.setText(item, false);
            }
        });





        conTypeView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                String item = adapterView.getItemAtPosition(position).toString();
                conTypeView.setText(item, false);
            }
        });

        conSizeView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                String item = adapterView.getItemAtPosition(position).toString();
                conSizeView.setText(item, false);
            }
        });
       surveyorView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                String item = adapterView.getItemAtPosition(position).toString();
                surveyorView.setText(item, false);
            }
        });

        conStatusView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                String item = adapterView.getItemAtPosition(position).toString();
                //custom Toast
                LayoutInflater inflater = getLayoutInflater();
                View customToastLayout = inflater.inflate(R.layout.activity_custom_toast, (ViewGroup) findViewById(R.id.custom_toast_container));
                TextView txtMessage = customToastLayout.findViewById(R.id.text);
                Toast mToast = new Toast(getApplicationContext());
                mToast.setDuration(Toast.LENGTH_LONG);
                mToast.setView(customToastLayout);

                if (item.equals("Damaged"))
                {
                    if (CheckAllFields())
                    {
                        CameraActivity camAct = new CameraActivity();
                        if (camAct.isValidContainerNumber(containerNumberView.getText().toString())) {
                            conStatusView.setText(item, false);
                            dialog = createDialog("Damaged");
                            TextView t = dialog.findViewById(R.id.conMsg);
                            t.setText(containerNumberView.getText().toString());
                            dialog.show();
                        } else {
                            txtMessage.setText("Please enter the valid Container number");
                            mToast.show();
                        }

                    } else
                    {
                        conStatusView.setText("");
                        txtMessage.setText("All Fields are required");
                        mToast.show();
                    }
                }
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu,menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if(item.getItemId() == R.id.logout)
        {

            AlertDialog alert = alert();
            alert.show();

        }

        return true;
    }

    public AlertDialog alert() {

        AlertDialog.Builder builder = new AlertDialog.Builder(UserFormActivity.this);
        builder.setTitle("Confirmation PopUp!").
                setMessage("You sure, that you want to logout?");
        builder.setPositiveButton("Yes",
                new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        session.Clear();
                        Intent intent = new Intent(UserFormActivity.this,LoginActivity.class);
                        startActivity(intent);
                    }
                });
        builder.setNegativeButton("No",
                new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        dialog.cancel();
                    }
                });

        return builder.create();
    }

    private void loadCyclesList() {
        try
        {
            DBHelper.loadCycles(UserFormActivity.this,new MyListCallback() {
                @Override
                public void onCallback(ArrayList<String> arrayList) {
                    cycles = arrayList;
                    if (cycles != null) {
                        loadedCycles= new String[cycles.size()];
                        loadedCycles = cycles.toArray(loadedCycles);
                        setDropdowns(cycleView, loadedCycles);
                    }
                }
            });

        }
        catch (Exception ex) {
           Toast.makeText(UserFormActivity.this,"Error in Loading Cycles list!",Toast.LENGTH_SHORT).show();
        }

    }

    private void loadActivitiesList() {

        LayoutInflater inflater = getLayoutInflater();
        View customToastLayout = inflater.inflate(R.layout.activity_custom_toast, (ViewGroup) findViewById(R.id.custom_toast_container));
        TextView txtMessage = customToastLayout.findViewById(R.id.text);
        Toast mToast = new Toast(getApplicationContext());
        mToast.setDuration(Toast.LENGTH_LONG);
        mToast.setView(customToastLayout);

        try
        {
            DBHelper.loadActivities(UserFormActivity.this,new MyListCallback() {
                @Override
                public void onCallback(ArrayList<String> arrayList) {
                    activities = arrayList;
                    if (activities != null) {
                        loadedActivities= new String[activities.size()];
                        loadedActivities = activities.toArray(loadedActivities);
                        setDropdowns(activityView, loadedActivities);
                    }
                }
            });

        }
        catch (Exception ex) {
            txtMessage.setText("Error in Loading Activities list");
            mToast.show();
        }

    }


    public void loadSurveyorList()
    {

        LayoutInflater inflater = getLayoutInflater();
        View customToastLayout = inflater.inflate(R.layout.activity_custom_toast, (ViewGroup) findViewById(R.id.custom_toast_container));
        TextView txtMessage = customToastLayout.findViewById(R.id.text);
        Toast mToast = new Toast(getApplicationContext());
        mToast.setDuration(Toast.LENGTH_LONG);
        mToast.setView(customToastLayout);

        try
        {
               DBHelper.LoadSurveyors(selectedLocation,new MyListCallback() {
                    @Override
                    public void onCallback(ArrayList<String> arrayList) {
                        surveyors = arrayList;
                        if (surveyors != null) {
                            loadedSurveyors = new String[surveyors.size()];
                            loadedSurveyors = surveyors.toArray(loadedSurveyors);
                            setDropdowns(surveyorView, loadedSurveyors);
                        }
                    }
                });

        }
        catch (Exception ex) {
            txtMessage.setText("Error in Loading Surveyors list");
            mToast.show();
        }

    }

    public Dialog createDialog(String conStatus)
    {
        //Dialog to confirm the Container No
        dialog = new Dialog(UserFormActivity.this);
        dialog.setContentView(R.layout.custom_dialog_layout);
        Objects.requireNonNull(dialog.getWindow()).setBackgroundDrawable(getDrawable(R.drawable.custom_dialog_background));
        dialog.getWindow().setLayout(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        dialog.setCancelable(false); //Optional
        dialog.getWindow().getAttributes().windowAnimations = R.style.DialogAnimation; //Setting the animations to dialog

        Button Okay = dialog.findViewById(R.id.btn_okay);
        Button Cancel = dialog.findViewById(R.id.btn_cancel);

        Okay.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent;
                if (conStatus.equals("Damaged")) {

                    HashMap<String, Object> Activity = getFilledData(conStatus);
                    intent = new Intent(UserFormActivity.this, DamagedContainerActivity.class);
                    intent.putExtra("map", Activity);
                    intent.putExtra("masterImg",uri.get(0).toString());
                    startActivity(intent);
                } else {
                    dialog.dismiss();
                    progressBarHolder.setVisibility(View.VISIBLE);
                   // getWindow().setFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE, WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE);
                    saveData();
                }
            }
        });

        Cancel.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dialog.dismiss();
            }
        });

        return dialog;

    }

    public void saveData()
    {
        LayoutInflater inflater = getLayoutInflater();
        View customToastLayout = inflater.inflate(R.layout.activity_custom_toast, (ViewGroup) findViewById(R.id.custom_toast_container));
        TextView txtMessage = customToastLayout.findViewById(R.id.text);
        Toast mToast = new Toast(getApplicationContext());
        mToast.setDuration(Toast.LENGTH_LONG);
        mToast.setView(customToastLayout);
        googleDriveHelper.signIn(new MySaveCallBack() {
            @Override
            public void onCallbackForSaveData(boolean status)
            {
                if(status) {

                }
                else {
                    Toast.makeText(UserFormActivity.this, "Google Drive Error!", Toast.LENGTH_SHORT).show();
                }

            }
        });
    }

    public HashMap<String, Object> getFilledData(String conStatus)
    {

        HashMap<String, Object> Activity = new HashMap<>();

        Activity.put("ContainerNumber", containerNumberView.getText().toString());
        Activity.put("ContainerStatus", conStatusView.getText().toString());
        DateTimeFormatter d = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss a");
        LocalDateTime now = LocalDateTime.now(ZoneId.of("Asia/Kolkata"));
        Activity.put("CreatedTime", d.format(now).toString());//new Timestamp(Instant.now())
        Activity.put("Activity", activityView.getText().toString());
        Activity.put("Cycle", cycleView.getText().toString());
        Activity.put("Location", locView.getText().toString());
        Activity.put("Size", conSizeView.getText().toString());
        Activity.put("Surveyor", surveyorView.getText().toString());
        Activity.put("UpdatedTime", d.format(now).toString());
        Activity.put("ShippingLine", shippingLineTextView.getText().toString());
        if (!conStatus.equals("Damaged")) {
            Activity.put("Remark", remark.getText().toString());
        };
        return Activity;
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data)
    {
        ContentResolver contentResolver = getContentResolver();
        super.onActivityResult(requestCode, resultCode, data);
        if ((requestCode == 1 || requestCode == 123) & resultCode == Activity.RESULT_OK) {
            if (data != null) {
                if (data.getClipData() != null) {
                    try
                    {
                        int x = data.getClipData().getItemCount();
                        for (int i = 0; i < x; i++)
                        {

                            Bitmap photo = MediaStore.Images.Media.getBitmap(contentResolver, data.getClipData().getItemAt(i).getUri());
                            if(photo.getWidth()>1000 && photo.getHeight()>1000)
                            {
                                uri.add(data.getClipData().getItemAt(i).getUri());
                                adapter.notifyDataSetChanged();
                            }
                            else
                            {
                                Toast.makeText(UserFormActivity.this,"Poor quality! Upload another image!",Toast.LENGTH_SHORT).show();

                            }
                        }
                    }
                    catch(Exception e) {
                        Toast.makeText(UserFormActivity.this,"Image Error",Toast.LENGTH_SHORT).show();
                    }
                } else if (data.getData() != null) {
                    String imageURL = data.getData().getPath();
                    uri.add(Uri.parse(imageURL));

                }
            } else {
                try {
                    Bitmap photo = MediaStore.Images.Media.getBitmap(contentResolver, cam_uri);
                    if(photo.getWidth()>1000 && photo.getHeight()>1000)
                    {
                        uri.add(cam_uri);
                        adapter.notifyDataSetChanged();
                    }
                    else
                    {
                        Toast.makeText(UserFormActivity.this,"Poor quality! Upload another image!",Toast.LENGTH_SHORT).show();

                    }
                }
                catch (Exception e)
                {
                    Toast.makeText(UserFormActivity.this,"Image Error",Toast.LENGTH_SHORT).show();

                }
            }
        }
        else if (requestCode == 2 & resultCode == Activity.RESULT_OK) {
            googleDriveHelper.handleSignInResult(new MySaveCallBack(){
                @Override
                public void onCallbackForSaveData(boolean status)
                {
                    if(status)
                    {
                        try {
                            DateTimeFormatter d = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss a");
                            LocalDateTime now = LocalDateTime.now(ZoneId.of("Asia/Kolkata"));
                            String folderName = locView.getText().toString()+"_"+containerNumberView.getText().toString()+"_"+d.format(now).toString();
                            googleDriveHelper.createFolder(new CreateFolderCallBack(){
                                @Override
                                public void onCallBackCreateFolder(boolean status,String folderId)
                                {
                                    final int[] count = {0};
                                    if(status)
                                    {
                                        if (uri!=null)
                                        {
                                            for (Uri u:uri)
                                            {
                                                String filePath = getRealPathFromURI(u,UserFormActivity.this);                                                getRealPathFromURI(u,UserFormActivity.this);
                                                java.io.File file = new java.io.File(filePath);
                                                googleDriveHelper.uploadFileToDrive(new CreateFolderCallBack() {
                                                    @Override
                                                    public void onCallBackCreateFolder(boolean status,String folderId) {
                                                        if(status)
                                                        {
                                                            count[0] = count[0] +1;
                                                            if(count[0] == uri.size())
                                                            {
                                                                Map<String, Object> Activity = getFilledData("Sound");
                                                                Activity.put("ImageLink","https://drive.google.com/drive/folders/"+folderId);
                                                                DBHelper.SaveDetails(new MySaveCallBack() {
                                                                    @Override
                                                                    public void onCallbackForSaveData(boolean status) {
                                                                        if (status) {
                                                                            progressBarHolder.setVisibility(View.GONE);
                                                                            //getWindow().clearFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE);
                                                                            Toast.makeText(UserFormActivity.this, "Data saved", Toast.LENGTH_SHORT).show();
                                                                            Intent intent = new Intent(UserFormActivity.this, CameraActivity.class);
                                                                            startActivity(intent);
                                                                        } else {
                                                                            Toast.makeText(UserFormActivity.this, "Failed", Toast.LENGTH_SHORT).show();
                                                                        }

                                                                    }
                                                                }, Activity);
                                                            }
                                                        }
                                                    }
                                                },file, folderId);
                                            }
                                        }

                                    }
                                    else
                                    {
                                        Toast.makeText(UserFormActivity.this,"Error in creating Folder in Google Drive" , Toast.LENGTH_SHORT).show();
                                    }

                                }
                            },folderName,session.getLoc());


                        }
                        catch(Exception e)
                        {
                            Toast.makeText(UserFormActivity.this,"Error in creating Folder in Google Drive" , Toast.LENGTH_SHORT).show();
                            Log.d("Drive",  e.toString());
                        }
                    }
                    else
                    {
                        Toast.makeText(UserFormActivity.this,"Error in Sign In to the Google Account" , Toast.LENGTH_SHORT).show();

                    }

                }
            },data);


        }


    }


public String getRealPathFromURI(Uri contentUri, Context a) {
    String[] proj = { MediaStore.Images.Media.DATA };
    Cursor cursor = getContentResolver().query(contentUri, proj, null, null, null);
    cursor.moveToFirst();
    int columnIndex = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
    String filePath = cursor.getString(columnIndex);
    cursor.close();
    return filePath;
    }



    public void setDropdowns(AutoCompleteTextView autoCompleteTextView, String[] values)
    {
        adapterItems = new ArrayAdapter<String>(this, R.layout.list_item, values);
        autoCompleteTextView.setAdapter(adapterItems);
    }

    public void moveToNext(View view)
    {

        LayoutInflater inflater = getLayoutInflater();
        View customToastLayout = inflater.inflate(R.layout.activity_custom_toast, (ViewGroup) findViewById(R.id.custom_toast_container));
        TextView txtMessage = customToastLayout.findViewById(R.id.text);
        Toast mToast = new Toast(getApplicationContext());
        mToast.setDuration(Toast.LENGTH_LONG);
        mToast.setView(customToastLayout);

        if (CheckAllFields()) {
            if (recyclerView.getAdapter().getItemCount() > 0) {
                CameraActivity camAct = new CameraActivity();
                if (camAct.isValidContainerNumber(containerNumberView.getText().toString())) {
                    dialog = createDialog("Sound");
                    TextView t = dialog.findViewById(R.id.conMsg);
                    t.setText(containerNumberView.getText().toString());
                    dialog.show();
                } else {
                    txtMessage.setText("Please enter the valid Container number");
                    mToast.show();
                }
            } else {
                txtMessage.setText("Please upload atleast 1 image to continue");
                mToast.show();
            }
        } else {
            txtMessage.setText("All Fields are required");
            mToast.show();
        }

    }

    private boolean CheckAllFields()
    {
        boolean retValue = true;
        if (dateTime.length() == 0) {
            return false;
        }

        if (containerNumberView.getText().toString().isEmpty() || activityView.getText().toString().isEmpty() || cycleView.getText().toString().isEmpty()||locView.getText().toString().isEmpty() || surveyorView.getText().toString().isEmpty() || conTypeView.getText().toString().isEmpty() || conSizeView.getText().toString().isEmpty() || conStatusView.getText().toString().isEmpty() || shippingLineTextView.getText().toString().isEmpty())
        {
            return false;
        }
        return retValue;
    }
}